---
apiVersion: "v1"
kind: "ImageStream"
metadata: 
  name: "petclinic" 
---
apiVersion: "v1"
kind: "BuildConfig"
metadata:
  name: "petclinic-build"
spec:
  source:
    type: "Dockerfile"
    dockerfile: "FROM tomcat:9.0-alpine\nLABEL version = \"1.1.3\"\nRUN wget $ARTIFACT_URL -O /usr/local/tomcat/webapps/petclinic.war"
  strategy:
    type: "Docker"
    dockerStrategy:
      from:
        kind: "DockerImage"
        name: "tomcat:9.0-alpine"
      env:
        - name: "ARTIFACT_URL"
          value: "http://nexus3.petclinic-build.svc:8081/repository/maven-snapshots/org/springframework/samples/spring-petclinic/1.5.2-SNAPSHOT/spring-petclinic-1.5.2-20171129.181122-16.jar"
  output:
    to:
      kind: "ImageStreamTag"
      name: "petclinic:latest"